name: Create Release
description: Create Release
inputs:
  version: 
    required: true
    type: string
  mode: 
    required: true
    type: string
outputs:
  upload_url:
    value: ${{ steps.release.outputs.upload_url }}
  mode:
    value: ${{ inputs.mode }}  
  version:
    value: ${{ inputs.version }}  

runs:
  using: "composite"
  steps:
- name: set version
  run: |
    echo "RELEASE_NAME=${VERSION}" >> $GITHUB_ENV
    echo "TAG_NAME=${MODE}-${VERSION}" >> $GITHUB_ENV
  shell: bash    
  env: 
    VERSION: ${{ inputs.version }}
    MODE: ${{ inputs.mode }}
    
- name: create release
  id: release
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  with:
    tag_name: ${{ env.TAG_NAME }}
    release_name: ${{ env.RELEASE_NAME }}
    draft: false
    prerelease: false 
  
