name: Build Component
description: Build Component
inputs:
  tool4d_download_url:
    required: false
    type: string
  tool4d_executable_path: 
    required: true
    type: string
  startup_method: 
    required: true
    type: string  
  project_path: 
    required: true
    type: string  
  user_param: 
    required: true
    type: string  
    
runs:
  using: "composite"
  steps:
    - name: execute startup method
      run: |
        "${TOOL4D_EXECUTABLE_PATH}" "${PROJECT_PATH}" --user-param="${USER_PARAM}" --startup-method="${PROJECT_STARTUP_METHOD}" --create-data
      shell: bash
      env:
        TOOL4D_EXECUTABLE_PATH: ${{ inputs.tool4d_executable_path }}
        TOOL4D_DOWNLOAD_URL: ${{ inputs.tool4d_download_url }}
        PROJECT_STARTUP_METHOD: ${{ inputs.startup_method }}
        PROJECT_PATH: ${{ inputs.project_path }}
        USER_PARAM: ${{ user_param }}
