name: Publish
  
on:
  workflow_dispatch:
    inputs:
        mode:
          type: choice
          description: semantic versioning
          options: 
          - patch
          - minor 
          - major
          required: true

env: 
  project_path: rezept/Project/rezept.4DProject
  
jobs:

  publish:
    permissions: write-all
    runs-on: [macos-latest]
    steps:

      - name: configure
        id: configure
        run: |
          if [ ${mode} = '' ]; then
          echo "mode=patch" >> $GITHUB_OUTPUT          
          else
          echo "mode=${mode}" >> $GITHUB_OUTPUT
          fi
          echo "project_path=${GITHUB_WORKSPACE}/${project_path}" >> $GITHUB_OUTPUT 
        shell: bash
        env:
          mode: ${{ inputs.mode }} 

      - name: checkout 
        uses: actions/checkout@v4

      - name: set version
        id: version
        uses: miyako/4D/.github/actions/package-set-version@v1
        with:
          mode: ${{ inputs.mode }}

      - name: get tag
        id: tag
        run: |
          path="${GITHUB_WORKSPACE}/package.json"
          release_name=$(cat "${path}" | jq -r '.release_name')    
          echo "release_name=${release_name}" >> $GITHUB_OUTPUT 
          
      - name: get tool version
        id: tool
        uses: miyako/4D/.github/actions/tool4d-get-version@v1
        
      - name: get tool4d
        id: get
        uses: miyako/4D/.github/actions/tool4d-download@v1
        with:
          platform: ${{ steps.tool.outputs.platform }}
          branch: ${{ steps.tool.outputs.branch }}
          version: ${{ steps.tool.outputs.version }}
          build: ${{ steps.tool.outputs.build }}
          arch: ${{ steps.tool.outputs.arch }}

      - name: generate
        id: generate
        run: |
          tool4d.app/Contents/MacOS/tool4d "${PROJECT_PATH}" --skip-onstartup --startup-method=regenerate --user-param="regenerate,export" --create-data
        env: 
          PROJECT_PATH: ${{ steps.configure.outputs.project_path }} 
          
      - name: build
        id: build
        uses: miyako/4D/.github/actions/build-component@v1
        with: 
          project_path: ${{ steps.configure.outputs.project_path }}

      - name: setup  
        id: setup
        run: |
          echo "project_path=${GITHUB_WORKSPACE}/example/Project/example.4DProject" >> $GITHUB_OUTPUT
          KEYCHAIN_PATH="${RUNNER_TEMP}/temp.keychain-db"
          CERTIFICATE_PATH="${RUNNER_TEMP}/Developer ID Application.p12"
          echo "KEYCHAIN_PATH=${KEYCHAIN_PATH}" >> $GITHUB_OUTPUT
          echo "CERTIFICATE_PATH=${CERTIFICATE_PATH}" >> $GITHUB_OUTPUT  

      # cleanup in case of self-hosted runner
      - name: delete keychain
        continue-on-error: true
        run: |
          security delete-keychain "${KEYCHAIN_PATH}"
        env:   
          KEYCHAIN_PATH: ${{ steps.setup.outputs.KEYCHAIN_PATH }}

      - name: install credentials
        continue-on-error: true
        run: |        
          echo -n "${APPLE_DEVELOPER_ID_CERTIFICATE}" | base64 --decode -o "${CERTIFICATE_PATH}"
          security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
          security default-keychain -s "${KEYCHAIN_PATH}"
          security set-keychain-settings -t 21600 "${KEYCHAIN_PATH}"
          security unlock-keychain -p "{$KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
          security import "${CERTIFICATE_PATH}" -P "${APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD}" -t cert -f pkcs12 -k "${KEYCHAIN_PATH}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "{$KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        env:
          CERTIFICATE_PATH: ${{ steps.setup.outputs.CERTIFICATE_PATH }}
          APPLE_DEVELOPER_ID_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE }}
          APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH: ${{ steps.setup.outputs.KEYCHAIN_PATH }}

      - name: codesign
        id: codesign
        uses: miyako/4D/.github/actions/deployment-codesign-product@v1
        with: 
          sign: ${{ secrets.CODESIGN_APPLE_ID }} 
          keychain: ${{ steps.setup.outputs.KEYCHAIN_PATH }}
          apple_id: ${{ secrets.NOTARYTOOL_APPLE_ID }}         
          team_id: ${{ secrets.NOTARYTOOL_TEAM_ID }}   
          password: ${{ secrets.NOTARYTOOL_PASSWORD }}
          product_path: ${{ steps.build.outputs.product_path }}

      - name: zip
        id: zip
        uses: miyako/4D/.github/actions/deployment-create-zip@v1
        with: 
          dmg_path: ${{ steps.codesign.outputs.dmg_path }}
          zip_path: ${{ steps.codesign.outputs.zip_path }}

      - name: upload assets
        id: upload
        uses: miyako/4D/.github/actions/deployment-release-assets@v1
        with: 
          dmg_path: ${{ steps.zip.outputs.dmg_path }}
          zip_path: ${{ steps.zip.outputs.zip_path }}    
          tag_name: ${{ steps.version.outputs.version }}   
          release_name: ${{ steps.tag.outputs.release_name }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          
      - name: upload 1
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: コメント.zip
          asset_name: data.1.zip
          asset_content_type: application/zip   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 2
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 医薬品.zip
          asset_name: data.2.zip
          asset_content_type: application/zip  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 3
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 記載事項等.zip
          asset_name: data.3.zip
          asset_content_type: application/zip  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 4
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 修飾語.zip
          asset_name: data.4.zip
          asset_content_type: application/zip  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 5
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 傷病名.zip
          asset_name: data.5.zip
          asset_content_type: application/zip  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 6
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 診療行為.zip
          asset_name: data.6.zip
          asset_content_type: application/zip     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 7
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 単位.zip
          asset_name: data.7.zip
          asset_content_type: application/zip   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 8
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 地方公費.zip
          asset_name: data.8.zip
          asset_content_type: application/zip   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: upload 9
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload.outputs.upload_url }}
          asset_path: 特定器材.zip
          asset_name: data.9.zip
          asset_content_type: application/zip     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
